/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Lichdatphong;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author HOÀNGQUANGHUY
 */
public class DrashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DrashBoard
     */
    ArrayList<Lichdatphong> list;
    DefaultTableModel model;
    
    public DrashBoard() {
        initComponents();
        this.setLocationRelativeTo(null);
        list= new ArrayList<Lichdatphong>();
        model = (DefaultTableModel) tbdatphong.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        textMaphong = new javax.swing.JLabel();
        txtGiaphong = new javax.swing.JTextField();
        textLoaiphong = new javax.swing.JLabel();
        txtLoaiphong = new javax.swing.JTextField();
        ImageRoom = new javax.swing.JLabel();
        btnDatphong = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        textTenphong = new javax.swing.JLabel();
        txtMaphong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdatphong = new javax.swing.JTable();
        textGiaphong = new javax.swing.JLabel();
        txtTenphong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        textMaphong.setText("Mã phòng:");
        jPanel1.add(textMaphong);
        textMaphong.setBounds(10, 80, 61, 16);
        jPanel1.add(txtGiaphong);
        txtGiaphong.setBounds(90, 200, 130, 22);

        textLoaiphong.setText("Loại Phòng:");
        jPanel1.add(textLoaiphong);
        textLoaiphong.setBounds(10, 160, 67, 16);
        jPanel1.add(txtLoaiphong);
        txtLoaiphong.setBounds(90, 160, 130, 22);
        jPanel1.add(ImageRoom);
        ImageRoom.setBounds(10, 230, 210, 116);

        btnDatphong.setText("Đặt Phòng");
        btnDatphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatphongActionPerformed(evt);
            }
        });
        jPanel1.add(btnDatphong);
        btnDatphong.setBounds(10, 360, 91, 25);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(130, 360, 90, 25);

        textTenphong.setText("Tên phòng:");
        jPanel1.add(textTenphong);
        textTenphong.setBounds(10, 120, 66, 16);
        jPanel1.add(txtMaphong);
        txtMaphong.setBounds(90, 80, 130, 22);

        tbdatphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã phòng", "Tên phòng", "Loại phòng", "Giá phòng", "Tình trạng"
            }
        ));
        jScrollPane1.setViewportView(tbdatphong);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(240, 80, 790, 310);

        textGiaphong.setText("Giá phòng:");
        jPanel1.add(textGiaphong);
        textGiaphong.setBounds(10, 200, 62, 16);
        jPanel1.add(txtTenphong);
        txtTenphong.setBounds(90, 120, 130, 22);

        jTabbedPane1.addTab("Drasboard", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phòng", "Tên phòng", "Loại phòng", "Giá phòng", "Tình trạng", "Ghi chú"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Thêm");

        jButton2.setText("Xóa");

        jButton3.setText("Sửa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );

        jTabbedPane1.addTab("Room", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Service", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Custumer", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Service", jPanel5);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 1040, 480);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí Khách Sạn Mường Thanh");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 0, 620, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtMaphong.setText("");
        txtMaphong.setText("");
        txtTenphong.setText("");
        txtLoaiphong.setText("");
        txtGiaphong.setText("");

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDatphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatphongActionPerformed

        Lichdatphong Beo=new Lichdatphong();
        Beo.setMaPhong(Integer.parseInt(txtMaphong.getText()));
        Beo.setTenPhong(txtTenphong.getText());
        Beo.setLoaiPhong(txtLoaiphong.getText());
        Beo.setGiaPhong(Double.parseDouble(txtGiaphong.getText()));
        list.add(Beo);
        showResult();

    }//GEN-LAST:event_btnDatphongActionPerformed
    int i=0;
    public void showResult()
    {
        Lichdatphong  s=list.get(list.size()-1);
    model.addRow(new Object[]{
        i++,s.getMaPhong(),s.getTenPhong(),s.getLoaiPhong(),s.getGiaPhong()
    
    });
            }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageRoom;
    private javax.swing.JButton btnDatphong;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbdatphong;
    private javax.swing.JLabel textGiaphong;
    private javax.swing.JLabel textLoaiphong;
    private javax.swing.JLabel textMaphong;
    private javax.swing.JLabel textTenphong;
    private javax.swing.JTextField txtGiaphong;
    private javax.swing.JTextField txtLoaiphong;
    private javax.swing.JTextField txtMaphong;
    private javax.swing.JTextField txtTenphong;
    // End of variables declaration//GEN-END:variables
}
