/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import DAL.DAL;
import DTO.Phong;


/**
 *
 * @author khoa
 */
public class formPhong extends javax.swing.JFrame {

    /**
     * Creates new form formPhong
     */
    ArrayList<Phong> list;
    DefaultTableModel model;
    public formPhong() {
        initComponents();
        list= new DAL().GetPhong();
        model = (DefaultTableModel) tbPhong.getModel();
       ShowTable();
    }
    int i=0;
    void ShowTable()
    {
        for (Phong Beo : list)
        {
            model.addRow(new Object[]{Beo.getMaPhong(),Beo.getTenPhong(),Beo.getLoaiPhong(),Beo.getGiaPhong(),Beo.getTinhTrang(),Beo.getGhiChu()});
        }
    }
    public void showResult()
    {
        Phong s=list.get(list.size()-1);
    model.addRow(new Object[]{
        s.getMaPhong(),s.getTenPhong(),s.getLoaiPhong(),s.getGiaPhong(),s.getTinhTrang(),s.getGhiChu()});
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbQuanLiPhong = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPhong = new javax.swing.JTable();
        paneThongTinPhong = new javax.swing.JPanel();
        textMaPhong = new javax.swing.JLabel();
        textTenPhong = new javax.swing.JLabel();
        textLoaiPhong = new javax.swing.JLabel();
        textGiaPhong = new javax.swing.JLabel();
        textGhiChu = new javax.swing.JLabel();
        textTinhTrang = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtTenPhong = new javax.swing.JTextField();
        txtLoaiPhong = new javax.swing.JTextField();
        txtGiaPhong = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtTinhTrang = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbQuanLiPhong.setBackground(new java.awt.Color(102, 102, 102));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("QUẢN LÝ PHÒNG");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tbPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Loại Phòng", "Giá Phòng", "Tình Trạng", "Ghi Chú"
            }
        ));
        tbPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbPhong);

        paneThongTinPhong.setBackground(new java.awt.Color(255, 102, 102));
        paneThongTinPhong.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Phòng"));

        textMaPhong.setText("Mã Phòng");

        textTenPhong.setText("Tên Phòng");

        textLoaiPhong.setText("Loại Phòng");

        textGiaPhong.setText("Giá Phòng");

        textGhiChu.setText("Ghi Chú");

        textTinhTrang.setText("Tình Trạng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/THEM.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/THOAT.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CLEAR.png"))); // NOI18N
        btnClear.setText("  Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneThongTinPhongLayout = new javax.swing.GroupLayout(paneThongTinPhong);
        paneThongTinPhong.setLayout(paneThongTinPhongLayout);
        paneThongTinPhongLayout.setHorizontalGroup(
            paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinPhongLayout.createSequentialGroup()
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneThongTinPhongLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textMaPhong)
                                .addComponent(textTenPhong)
                                .addComponent(textGiaPhong)
                                .addComponent(textTinhTrang)
                                .addComponent(textGhiChu))
                            .addGroup(paneThongTinPhongLayout.createSequentialGroup()
                                .addComponent(textLoaiPhong)
                                .addGap(2, 2, 2)))
                        .addGap(87, 87, 87)
                        .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(txtTenPhong)
                                .addComponent(txtLoaiPhong)
                                .addComponent(txtGiaPhong))
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(paneThongTinPhongLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThoat)
                            .addGroup(paneThongTinPhongLayout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(83, 83, 83)))
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneThongTinPhongLayout.setVerticalGroup(
            paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneThongTinPhongLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMaPhong)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTenPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLoaiPhong)
                    .addComponent(txtLoaiPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textGiaPhong)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTinhTrang)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textGhiChu)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(paneThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnClear))
                .addGap(26, 26, 26)
                .addComponent(btnThoat)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tbQuanLiPhongLayout = new javax.swing.GroupLayout(tbQuanLiPhong);
        tbQuanLiPhong.setLayout(tbQuanLiPhongLayout);
        tbQuanLiPhongLayout.setHorizontalGroup(
            tbQuanLiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbQuanLiPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbQuanLiPhongLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        tbQuanLiPhongLayout.setVerticalGroup(
            tbQuanLiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbQuanLiPhongLayout.createSequentialGroup()
                .addGroup(tbQuanLiPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbQuanLiPhongLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tbQuanLiPhongLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(paneThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbQuanLiPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbQuanLiPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhongMouseClicked
        // TODO add your handling code here:
        int i = tbPhong.getSelectedRow();
        TableModel model = tbPhong.getModel();
        txtMaPhong.setText(model.getValueAt(i, 0).toString());
        txtTenPhong.setText(model.getValueAt(i, 1).toString());
        txtLoaiPhong.setText(model.getValueAt(i, 2).toString());
        txtGiaPhong.setText(model.getValueAt(i, 3).toString());
        txtGhiChu.setText(model.getValueAt(i, 4).toString());
        txtTinhTrang.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tbPhongMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       
        Phong Beo=new Phong();
        Beo.setMaPhong(Integer.parseInt(txtMaPhong.getText()));
        Beo.setTenPhong(txtTenPhong.getText());
        Beo.setLoaiPhong(txtLoaiPhong.getText());
        Beo.setGiaPhong(Integer.parseInt(txtGiaPhong.getText()));
        Beo.setTinhTrang(txtTinhTrang.getText());
        Beo.setGhiChu(txtGhiChu.getText());
        list.add(Beo);
        if (new DAL().addPhong(Beo))
                {
                    JOptionPane.showMessageDialog(rootPane, "Them Phong thanh cong vao Database");
                }
         else{
                    JOptionPane.showMessageDialog(rootPane, "Them Phong that bai");
                }
        showResult();
        

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát không ?", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtMaPhong.setText("");
        txtTenPhong.setText("");
        txtLoaiPhong.setText("");
        txtGiaPhong.setText("");
        txtGhiChu.setText("");
        txtTinhTrang.setText("");
        txtMaPhong.requestFocus();

    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel paneThongTinPhong;
    private javax.swing.JTable tbPhong;
    private javax.swing.JPanel tbQuanLiPhong;
    private javax.swing.JLabel textGhiChu;
    private javax.swing.JLabel textGiaPhong;
    private javax.swing.JLabel textLoaiPhong;
    private javax.swing.JLabel textMaPhong;
    private javax.swing.JLabel textTenPhong;
    private javax.swing.JLabel textTinhTrang;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtTenPhong;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
